### ISSUE TITLE
Polytomy error in tree file

### ISSUE THREAD

**Issue by DEYANGEIOZ** [michaelmiyagi/QuIBL#13]
Dear Miriammiyagi,
Thank you for your contribution on this amazing software. 
I managed to run the test data successfully, but I got error message for my own tree as the followings:
Tree 3 skipped due to polytomy.
Traceback (most recent call last):
  File "QuIBL.py", line 338, in <module>
    inputReader(sys.argv[1])
  File "QuIBL.py", line 334, in inputReader
    outputFormatter(outputDict,inputDict)
  File "QuIBL.py", line 299, in outputFormatter
    trees=getTripBranches(readin_Newick(inputDict['treefile']),canonOut)
  File "QuIBL.py", line 82, in getTripBranches
    if len(tree.expand_polytomies())>1:
  File "/home/think/software/QuIBL-master/venv/lib/python2.7/site-packages/ete3/coretype/tree.py", line 2260, in expand_polytomies
    raise TreeError("Found polytomy larger than current limit: %s" %n)
ete3.coretype.tree.TreeError: 'Found polytomy larger than current limit: \n   /-O74\n  |\n  |--O75\n  |\n  |--O78\n  |\n  |--O79\n  |\n  |--O82\n--|\n  |--O86\n  |\n  |--O88\n  |\n  |--O92\n  |\n  |--O96\n  |\n   \\-O112'
What might be the problem in my tree?
Thank you very much for your attention.

**Comment by miriammiyagi** [comment]
Hi! I think I wrote to you via email- but if anyone else has the same problem, QuIBL just requires that all trees be fully resolved (no polytomies).

Best,
Mia
